spring.application.name=abitov-api
server.servlet.context-path=/api
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.sql.init.mode=never

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:shalukhina;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

server.port=${SERVER_PORT:8080}

app.notification.reminder-days=${APP_NOTIFICATION_REMINDER_DAYS:30}
app.notification.overdue-days=${APP_NOTIFICATION_OVERDUE_DAYS:0}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=android.kotlin@bk.ru
spring.mail.password=gbid gnve taml gnvo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true