create table if not exists app_users (
    id bigint generated by default as identity primary key,
    first_name varchar(120) not null,
    last_name varchar(120) not null,
    email varchar(180) not null unique,
    password_hash varchar(255) not null,
    role varchar(32) not null,
    active boolean not null,
    phone varchar(50),
    created_at timestamp not null,
    last_login_at timestamp
);

create table if not exists courses (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    description varchar(1000),
    repeat_months integer not null,
    training_format varchar(120) not null,
    active boolean not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table if not exists enrollments (
    id bigint generated by default as identity primary key,
    client_id bigint not null,
    course_id bigint not null,
    teacher_id bigint,
    enrolled_at date not null,
    completed_at date,
    next_due_at date,
    status varchar(32) not null,
    notes varchar(2000),
    created_at timestamp not null,
    updated_at timestamp not null
);

create table if not exists notifications (
    id bigint generated by default as identity primary key,
    enrollment_id bigint,
    client_id bigint not null,
    recipient_email varchar(180) not null,
    notification_type varchar(32) not null,
    subject varchar(255) not null,
    message varchar(4000) not null,
    due_at date not null,
    created_at timestamp not null,
    sent_at timestamp,
    status varchar(32) not null,
    delivery_channel varchar(32) not null,
    failure_reason varchar(2000)
);
